-- Schema Migration from MySQL to PostgreSQL
-- Source: safira_novo.sql
-- Generated by Antigravity

-- --------------------------------------------------------
-- Users Table
-- Stores user account information, including login credentials,
-- personal details, and current balance.
-- --------------------------------------------------------
CREATE TABLE users (
    id SERIAL PRIMARY KEY,
    username VARCHAR(255) NOT NULL,
    email VARCHAR(258) NOT NULL,
    password VARCHAR(258),
    real_name VARCHAR(90),
    number_phone VARCHAR(20),
    balance DECIMAL(20,2) NOT NULL DEFAULT 0.00,
    requery DECIMAL(8,2) NOT NULL DEFAULT 0.00,
    bonus DECIMAL(20,2) NOT NULL DEFAULT 0.00,
    level INTEGER NOT NULL DEFAULT 0,
    score_level DECIMAL(8,2) NOT NULL DEFAULT 0.00,
    score_level_current VARCHAR(255) NOT NULL DEFAULT '0',
    unique_id VARCHAR(255),
    ip VARCHAR(255),
    is_admin INTEGER NOT NULL DEFAULT 0,
    avatar VARCHAR(520) DEFAULT '/img/userfyre.png',
    superadmin INTEGER NOT NULL DEFAULT 0,
    is_lowadmin INTEGER NOT NULL DEFAULT 0,
    is_moder INTEGER NOT NULL DEFAULT 0,
    is_youtuber INTEGER NOT NULL DEFAULT 0,
    fake INTEGER NOT NULL DEFAULT 0,
    time INTEGER NOT NULL DEFAULT 0,
    banchat INTEGER,
    banchat_reason TEXT,
    user_id INTEGER, -- Potentially a referrer ID or linked account
    ban INTEGER NOT NULL DEFAULT 0,
    ban_reason TEXT,
    link_trans INTEGER NOT NULL DEFAULT 0,
    link_reg INTEGER NOT NULL DEFAULT 0,
    ref_id VARCHAR(255),
    ref_money DECIMAL(20,2) NOT NULL DEFAULT 0.00,
    ref_money_all DECIMAL(20,2) NOT NULL DEFAULT 0.00,
    remember_token TEXT,
    isDeveloper INTEGER DEFAULT 0,
    cpf VARCHAR(12),
    zip_code INTEGER,
    street_name TEXT,
    street_number INTEGER,
    neighborhood VARCHAR(210),
    city VARCHAR(210),
    federal_unit VARCHAR(10),
    updated_at TIMESTAMP,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    token_new_pass VARCHAR(255)
);

-- --------------------------------------------------------
-- Game: Battle
-- Stores the state and results of the 'Battle' game rounds.
-- --------------------------------------------------------
CREATE TABLE battle (
    id SERIAL PRIMARY KEY,
    price DECIMAL(20,2) DEFAULT 0.00,
    commission DECIMAL(20,2),
    winner_team VARCHAR(255),
    winner_factor DECIMAL(20,2),
    winner_ticket INTEGER,
    status SMALLINT DEFAULT 0,
    hash VARCHAR(255),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP
);

-- --------------------------------------------------------
-- Game Bets: Battle
-- Stores individual bets placed by users on the 'Battle' game.
-- --------------------------------------------------------
CREATE TABLE battle_bets (
    id SERIAL PRIMARY KEY,
    game_id INTEGER,
    user_id INTEGER,
    price DECIMAL(20,2),
    color VARCHAR(255),
    win INTEGER DEFAULT 0,
    win_sum DECIMAL(20,2) NOT NULL DEFAULT 0.00,
    balType VARCHAR(255),
    fake INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP
);

-- --------------------------------------------------------
-- Game: Crash
-- Stores the state and results of the 'Crash' game rounds (multiplier, hash).
-- --------------------------------------------------------
CREATE TABLE crash (
    id SERIAL PRIMARY KEY,
    multiplier DECIMAL(20,2),
    profit DECIMAL(20,2) DEFAULT 0.00,
    hash VARCHAR(255),
    status INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP
);

-- --------------------------------------------------------
-- Game Bets: Crash
-- Stores individual bets placed by users on the 'Crash' game.
-- --------------------------------------------------------
CREATE TABLE crash_bets (
    id SERIAL PRIMARY KEY,
    user_id INTEGER,
    round_id INTEGER,
    price DECIMAL(20,2),
    withdraw DECIMAL(20,2),
    won DECIMAL(20,2) DEFAULT 0.00,
    status INTEGER NOT NULL DEFAULT 0,
    fake SMALLINT NOT NULL DEFAULT 0,
    balType VARCHAR(255),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP
);

-- --------------------------------------------------------
-- Game: Dice
-- Stores the state and results of the 'Dice' game.
-- --------------------------------------------------------
CREATE TABLE dice (
    id SERIAL PRIMARY KEY,
    user_id INTEGER,
    sum DECIMAL(20,2),
    perc DECIMAL(20,2) DEFAULT 0.00,
    vip DECIMAL(20,2) NOT NULL DEFAULT 0.00,
    num DECIMAL(20,2) DEFAULT 0.00,
    range_value VARCHAR(255), -- Renamed from 'range' which is a reserved keyword in some SQL dialects
    win INTEGER NOT NULL DEFAULT 0,
    win_sum DECIMAL(20,2),
    balType VARCHAR(255),
    fake INTEGER NOT NULL DEFAULT 0,
    hash TEXT,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP
);

-- --------------------------------------------------------
-- Game: Double
-- Stores the state and results of the 'Double' game (roulette-like colors).
-- --------------------------------------------------------
CREATE TABLE double_game ( -- Renamed from 'double' which is a reserved keyword
    id SERIAL PRIMARY KEY,
    winner_color VARCHAR(255),
    winner_number INTEGER NOT NULL DEFAULT 0,
    pot DOUBLE PRECISION NOT NULL DEFAULT 0.00,
    status INTEGER NOT NULL DEFAULT 0,
    hash VARCHAR(255),
    profit VARCHAR(255),
    ranked INTEGER NOT NULL DEFAULT 0,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- --------------------------------------------------------
-- Game Bets: Double
-- Stores individual bets placed by users on the 'Double' game.
-- --------------------------------------------------------
CREATE TABLE double_bets (
    id SERIAL PRIMARY KEY,
    user_id INTEGER DEFAULT 1,
    price DOUBLE PRECISION NOT NULL DEFAULT 0.00,
    balance VARCHAR(255) NOT NULL DEFAULT 'balance',
    game_id INTEGER NOT NULL DEFAULT 0,
    color VARCHAR(255),
    win INTEGER NOT NULL DEFAULT 0,
    win_sum DOUBLE PRECISION NOT NULL DEFAULT 0.00,
    fake INTEGER NOT NULL DEFAULT 0,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- --------------------------------------------------------
-- Game: Flip
-- Stores the state and results of the 'Flip' (Coinflip) game.
-- --------------------------------------------------------
CREATE TABLE flip (
    id SERIAL PRIMARY KEY,
    heads INTEGER,
    heads_from INTEGER,
    heads_to INTEGER,
    tails INTEGER,
    tails_from INTEGER,
    tails_to INTEGER,
    bank DECIMAL(20,2),
    winner_id INTEGER,
    winner_ticket INTEGER,
    winner_sum DECIMAL(20,2),
    balType VARCHAR(255),
    hash TEXT,
    status INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP
);

-- --------------------------------------------------------
-- Game: Hilo
-- Stores the state and results of the 'Hilo' (High-Low) game.
-- --------------------------------------------------------
CREATE TABLE hilo (
    id SERIAL PRIMARY KEY,
    card_name VARCHAR(255),
    card_amount INTEGER,
    card_section VARCHAR(255),
    card_sign VARCHAR(255),
    status INTEGER NOT NULL DEFAULT 0,
    profit DECIMAL(20,2) NOT NULL DEFAULT 0.00,
    hash TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP
);

-- --------------------------------------------------------
-- Game Bets: Hilo
-- Stores individual bets placed by users on the 'Hilo' game.
-- --------------------------------------------------------
CREATE TABLE hilo_bets (
    id SERIAL PRIMARY KEY,
    game_id INTEGER,
    user_id INTEGER,
    bet_type INTEGER,
    bet_x DOUBLE PRECISION,
    sum DECIMAL(20,2) DEFAULT 0.00,
    balance VARCHAR(255),
    win INTEGER NOT NULL DEFAULT 0,
    win_sum DECIMAL(20,2) DEFAULT 0.00,
    win_bonus DECIMAL(20,2) NOT NULL DEFAULT 0.00,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP
);

-- --------------------------------------------------------
-- Game: Jackpot
-- Stores the state and results of the 'Jackpot' game.
-- --------------------------------------------------------
CREATE TABLE jackpot (
    id SERIAL PRIMARY KEY,
    room VARCHAR(255),
    game_id INTEGER,
    winner_id INTEGER,
    winner_ticket INTEGER,
    winner_balance DECIMAL(20,2),
    winner_bonus DECIMAL(20,2),
    hash VARCHAR(255),
    status INTEGER DEFAULT 0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP
);

-- --------------------------------------------------------
-- Game Bets: Jackpot
-- Stores individual bets placed by users on the 'Jackpot' game.
-- --------------------------------------------------------
CREATE TABLE jackpot_bets (
    id SERIAL PRIMARY KEY,
    room VARCHAR(255),
    game_id INTEGER,
    user_id INTEGER,
    sum DECIMAL(20,2) NOT NULL DEFAULT 0.00,
    color VARCHAR(255),
    balance VARCHAR(255),
    win INTEGER NOT NULL DEFAULT 0,
    fake INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP
);

-- --------------------------------------------------------
-- Game: Roulette
-- Stores the state and results of the 'Roulette' game.
-- --------------------------------------------------------
CREATE TABLE roulette (
    id SERIAL PRIMARY KEY,
    winner_color VARCHAR(255),
    price DECIMAL(20,2),
    status INTEGER NOT NULL DEFAULT 0,
    hash TEXT,
    profit DECIMAL(20,2) NOT NULL DEFAULT 0.00,
    ranked INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP
);

-- --------------------------------------------------------
-- Game Bets: Roulette
-- Stores individual bets placed by users on the 'Roulette' game.
-- --------------------------------------------------------
CREATE TABLE roulette_bets (
    id SERIAL PRIMARY KEY,
    user_id INTEGER,
    game_id INTEGER,
    price DECIMAL(20,2),
    color VARCHAR(255),
    win INTEGER NOT NULL DEFAULT 0,
    win_sum DECIMAL(20,2) NOT NULL DEFAULT 0.00,
    balance VARCHAR(255),
    fake INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP
);

-- --------------------------------------------------------
-- Game: Wheel
-- Stores the state and results of the 'Wheel' game.
-- --------------------------------------------------------
CREATE TABLE wheel (
    id SERIAL PRIMARY KEY,
    winner_color VARCHAR(255),
    price DECIMAL(20,2),
    status INTEGER NOT NULL DEFAULT 0,
    hash TEXT,
    profit DECIMAL(20,2) NOT NULL DEFAULT 0.00,
    ranked INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP
);

-- --------------------------------------------------------
-- Game Bets: Wheel
-- Stores individual bets placed by users on the 'Wheel' game.
-- --------------------------------------------------------
CREATE TABLE wheel_bets (
    id SERIAL PRIMARY KEY,
    user_id INTEGER,
    game_id INTEGER,
    price DECIMAL(20,2),
    color VARCHAR(255),
    win INTEGER NOT NULL DEFAULT 0,
    win_sum DECIMAL(20,2) NOT NULL DEFAULT 0.00,
    balance VARCHAR(255),
    fake INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP
);

-- --------------------------------------------------------
-- Game: Towers
-- Stores the state and results of the 'Towers' game.
-- --------------------------------------------------------
CREATE TABLE towers (
    id BIGSERIAL PRIMARY KEY,
    user_id INTEGER NOT NULL,
    bet DOUBLE PRECISION NOT NULL,
    bombs INTEGER NOT NULL,
    currency VARCHAR(255) NOT NULL,
    field TEXT NOT NULL, -- JSON or serialized data
    revealed TEXT NOT NULL, -- JSON or serialized data
    coeff DOUBLE PRECISION NOT NULL DEFAULT 0.00,
    status INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMP,
    updated_at TIMESTAMP
);

-- --------------------------------------------------------
-- Game Rooms
-- Configuration for different game rooms (e.g., different bet limits).
-- --------------------------------------------------------
CREATE TABLE rooms (
    id SERIAL PRIMARY KEY,
    name VARCHAR(255),
    title VARCHAR(255),
    min DECIMAL(20,2) NOT NULL DEFAULT 1.00,
    max DECIMAL(20,2) NOT NULL DEFAULT 1000.00,
    bets INTEGER NOT NULL DEFAULT 3,
    time INTEGER NOT NULL DEFAULT 10,
    status INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP
);

-- --------------------------------------------------------
-- Payments
-- Logs incoming payment transactions.
-- --------------------------------------------------------
CREATE TABLE payments (
    id SERIAL PRIMARY KEY,
    user_id INTEGER,
    secret TEXT,
    order_id VARCHAR(255),
    sum DECIMAL(20,2),
    status INTEGER NOT NULL DEFAULT 0,
    system VARCHAR(255),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP,
    extra_info TEXT
);

-- --------------------------------------------------------
-- Withdrawals
-- Logs withdrawal requests and their status.
-- --------------------------------------------------------
CREATE TABLE withdraw (
    id SERIAL PRIMARY KEY,
    user_id INTEGER,
    value DECIMAL(8,2),
    valueWithCom DECIMAL(20,2),
    wallet VARCHAR(255),
    system VARCHAR(255),
    provider VARCHAR(255) NOT NULL DEFAULT 'asaas',
    status INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP
);

-- --------------------------------------------------------
-- Exchanges
-- Logs currency exchanges or internal transfers.
-- --------------------------------------------------------
CREATE TABLE exchanges (
    id SERIAL PRIMARY KEY,
    user_id INTEGER NOT NULL,
    sum DECIMAL(20,2),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP
);

-- --------------------------------------------------------
-- Sends
-- Logs user-to-user balance transfers.
-- --------------------------------------------------------
CREATE TABLE sends (
    id SERIAL PRIMARY KEY,
    sender INTEGER NOT NULL,
    receiver INTEGER NOT NULL,
    sum INTEGER NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- --------------------------------------------------------
-- Bonus
-- Configuration for bonuses.
-- --------------------------------------------------------
CREATE TABLE bonus (
    id SERIAL PRIMARY KEY,
    sum DECIMAL(20,2),
    bg VARCHAR(255),
    color VARCHAR(255),
    status INTEGER NOT NULL DEFAULT 1,
    type VARCHAR(255),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP
);

-- --------------------------------------------------------
-- Bonus Log
-- Logs bonuses awarded to users.
-- --------------------------------------------------------
CREATE TABLE bonus_log (
    id SERIAL PRIMARY KEY,
    user_id INTEGER,
    sum DECIMAL(20,2),
    remaining INTEGER,
    status INTEGER NOT NULL DEFAULT 0,
    type VARCHAR(255),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP
);

-- --------------------------------------------------------
-- Settings
-- Global application settings and configurations.
-- --------------------------------------------------------
CREATE TABLE settings (
    id SERIAL PRIMARY KEY,
    domain VARCHAR(255) DEFAULT 'webzow',
    sitename VARCHAR(255) DEFAULT 'webzow',
    title VARCHAR(255) DEFAULT 'webzow',
    description TEXT,
    keywords TEXT,
    site_disable INTEGER NOT NULL DEFAULT 0,
    vk_url TEXT,
    vk_support_link TEXT,
    vk_service_key TEXT,
    censore_replace VARCHAR(255) DEFAULT 'i ♥ webzow',
    chat_dep DECIMAL(20,2) DEFAULT 10.00,
    fakebets INTEGER NOT NULL DEFAULT 0,
    fake_min_bet DECIMAL(20,2) DEFAULT 0.10,
    fake_max_bet DECIMAL(20,2) DEFAULT 100.00,
    fk_mrh_ID INTEGER,
    fk_secret1 VARCHAR(255),
    fk_secret2 VARCHAR(255),
    fk_api VARCHAR(255),
    fk_wallet VARCHAR(255),
    payeer_mrh_ID INTEGER,
    payeer_secret1 VARCHAR(255),
    payeer_secret2 VARCHAR(255),
    payeer_account_ID VARCHAR(255),
    payeer_api_ID VARCHAR(255),
    payeer_api_pass VARCHAR(255),
    profit_koef DECIMAL(20,2) DEFAULT 1.30,
    profit_money DECIMAL(20,2) NOT NULL DEFAULT 0.00,
    jackpot_commission INTEGER DEFAULT 10,
    wheel_timer INTEGER DEFAULT 15,
    wheel_min_bet DECIMAL(20,2) DEFAULT 0.10,
    wheel_max_bet DECIMAL(20,2) DEFAULT 1000.00,
    wheel_rotate DECIMAL(20,2) DEFAULT 0.00,
    wheel_rotate2 DECIMAL(20,2) DEFAULT 0.00,
    wheel_rotate_start DECIMAL(20,2) DEFAULT 0.00,
    double_rotate DECIMAL(20,2) NOT NULL DEFAULT 0.00,
    double_rotate_start DECIMAL(20,2) NOT NULL DEFAULT 0.00,
    crash_min_bet DECIMAL(20,2) DEFAULT 0.10,
    crash_max_bet DECIMAL(20,2) DEFAULT 1000.00,
    crash_timer INTEGER DEFAULT 10,
    battle_timer INTEGER DEFAULT 10,
    battle_min_bet DECIMAL(20,2) DEFAULT 0.10,
    battle_max_bet DECIMAL(20,2) DEFAULT 1000.00,
    battle_commission INTEGER DEFAULT 10,
    dice_min_bet DECIMAL(20,2) DEFAULT 0.10,
    dice_max_bet DECIMAL(20,2) DEFAULT 1000.00,
    flip_commission INTEGER DEFAULT 15,
    flip_min_bet DECIMAL(20,2) DEFAULT 0.10,
    flip_max_bet DECIMAL(20,2) DEFAULT 1000.00,
    hilo_timer INTEGER NOT NULL DEFAULT 20,
    hilo_min_bet DECIMAL(20,2) NOT NULL DEFAULT 0.10,
    hilo_max_bet DECIMAL(20,2) NOT NULL DEFAULT 1000.00,
    hilo_bets INTEGER NOT NULL DEFAULT 3,
    tower_min_bet INTEGER,
    tower_max_bet INTEGER,
    exchange_min DECIMAL(20,2) DEFAULT 3000.00,
    exchange_curs INTEGER DEFAULT 3,
    ref_perc INTEGER DEFAULT 5,
    ref_sum DECIMAL(20,2) DEFAULT 0.50,
    min_ref_withdraw DECIMAL(20,2) DEFAULT 10.00,
    min_dep DECIMAL(20,2) DEFAULT 1.00,
    min_dep_withdraw DECIMAL(20,2) DEFAULT 50.00,
    requery_perc DECIMAL(8,2) NOT NULL DEFAULT 10.00,
    requery_bet_perc DECIMAL(8,2) DEFAULT 1.00,
    dep_bonus_min DECIMAL(20,2) NOT NULL DEFAULT 0.00,
    dep_bonus_perc DECIMAL(20,2) NOT NULL DEFAULT 0.00,
    bonus_group_time INTEGER DEFAULT 15,
    max_active_ref INTEGER DEFAULT 8,
    payeer_com_percent DECIMAL(20,2) DEFAULT 1.00,
    payeer_com_rub DECIMAL(20,2) DEFAULT 0.00,
    payeer_min DECIMAL(20,2) DEFAULT 10.00,
    qiwi_com_percent DECIMAL(20,2) DEFAULT 2.90,
    qiwi_com_rub DECIMAL(20,2) DEFAULT 0.00,
    qiwi_min DECIMAL(20,2) DEFAULT 10.00,
    yandex_com_percent DECIMAL(20,2) DEFAULT 0.00,
    yandex_com_rub DECIMAL(20,2) DEFAULT 0.00,
    yandex_min DECIMAL(20,2) DEFAULT 10.00,
    webmoney_com_percent DECIMAL(20,2) DEFAULT 5.00,
    webmoney_com_rub DECIMAL(20,2) DEFAULT 0.00,
    webmoney_min DECIMAL(20,2) DEFAULT 10.00,
    visa_com_percent DECIMAL(20,2) DEFAULT 4.00,
    visa_com_rub DECIMAL(20,2) DEFAULT 50.00,
    visa_min DECIMAL(20,2) DEFAULT 1000.00,
    mp_com_percent DECIMAL(20,2) DEFAULT 1.00,
    mp_com_brl DECIMAL(20,2) NOT NULL DEFAULT 0.00,
    mp_min DECIMAL(20,2) NOT NULL DEFAULT 10.00,
    double_next_result DECIMAL(11,0) NOT NULL DEFAULT -1,
    double_red_percent INTEGER NOT NULL DEFAULT 47,
    double_black_percent INTEGER NOT NULL DEFAULT 47,
    double_white_percent INTEGER NOT NULL DEFAULT 6,
    cpa_min_deposit_value INTEGER NOT NULL DEFAULT 40,
    repost_post_id VARCHAR(258),
    level_point_withdraw DECIMAL(8,2) NOT NULL DEFAULT 0.00
);
